### ISSUE TITLE
Use of images

### ISSUE THREAD

**Issue by mikera** [rogerallen/tweegeemee#13]
Hi there @rogerallen , loving the images coming out of tweegeemee!

Is it OK to freely use the images generated? I'd like to use a few of them as examples of computer generated artwork

**Comment by rogerallen** [comment]
Thanks for asking @mikera.  I was pondering this somewhat, but was only going to really consider the license if it came up.  So it has...

I looked on the Creative Commons website for their guidance and found this flowchart:
http://creativecommons.org.au/content/licensing-flowchart.pdf

_Am I ok with other people copying and distributing my content without asking my permission everytime?_

Yes, I am

_Am I ok with them changing and adapting the content? Will I allow remixing?_

Yes, I am

_Do I want to limit how others can release their remixes? ie. If they remix, their new content must be available to remix on the same terms._

Yes, I do.  I want them to keep their remixes available to remix, just as I am making these images available to remix.

_Am I ok with other people making money out of their reuse of the content?_

Yes, I am.  I would appreciate a cut if they use tweegeemee images in some major part of their new content, but I'm not going to lose sleep demanding it.  Hopefully, kharma is a motivator.  

That suggests I should use an **Attribution Share-Alike license**.  

Okay, I will make note of this...

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/StillImage" property="dct:title" rel="dct:type">Tweegeemee artwork</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

Is that acceptable, @mikera ?

**Comment by rogerallen** [comment]
[please note that I am not a lawyer] 

Well, looking a bit further, I see that perhaps I am overstepping my bounds with the above demands. 

From _COMPENDIUM OF U. S. COPYRIGHT OFFICE PRACTICES , Third Edition_ http://copyright.gov/comp3/chap900/ch900-visual-art.pdf

_906.6 Mechanical Processes and Random Selection_
The copyright law only protects works of authorship that are created by human beings.
Works made through purely mechanical processes or with an automated selection and
arrangement are not eligible for copyright protection. The U.S. Copyright Office will 
refuse to register a claim in a work that is created through the operation of a machine or
process without any human interaction, even if the design is randomly generated.

I read this as saying that the images tweegeemee creates **cannot** be copyrighted.  So, there you have it...  

I would still appreciate attribution, but apparently the images are non-copyrightable, so you may use them as you see fit.

**Comment by rogerallen** [comment]
I think another question that would have come up with the earlier CC-SA-4 license idea is:  What if you re-run the tweegeemee created code yourself (at the repl as I show in the README) and create an image with a different resolution  or cropping than the image posted by tweegeemee?  Now, what if you add a small border?  

Is it your own image, not tweegeemee's image?  I think it would be...

**Comment by mikera** [comment]
Haha interesting things to note about copyright law. You learn something new every day!.

Overall though I'm perfectly happy with the Creative Commons Attribution-ShareAlike 4.0 International License so I will abide by those terms (even I I don't technically have to....)

Thanks!
