### ISSUE TITLE
post a summary 

### ISSUE THREAD

**Issue by rogerallen** [rogerallen/tweegeemee#4]
once in a while, post some sort of summary

**Comment by rogerallen** [comment]
One idea is something like "thanks for being the top followers: foo, bar, baz!"

**Comment by bar** [comment]
@rogerallen Hey! me? what? please don't thanks :)

**Comment by rogerallen** [comment]
Hrm, apparently you cannot get a list of who favorited a tweet from the API.  So, I can't score my followers to rank them.
